### ISSUE TITLE
Add relational persona filters

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Identities#2]
```
app.filter.individual_persona.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { id: exact, uuid: exact, owner: exact, ownerUuid: exact, **individual.uuid: exact** }
        tags:
            - { name: api_platform.filter, id: app.individual_persona.search }
```

```
app.filter.staff_persona.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { id: exact, uuid: exact, owner: exact, ownerUuid: exact, **staff.uuid: exact** }
        tags:
            - { name: api_platform.filter, id: app.staff_persona.search }
```
